
query PRs {

  git_appletini: repository(name: "git_appletini", owner: "darvoid") {
      pullRequests(
        orderBy: { field: CREATED_AT, direction: ASC }
        first: 12
        states: [OPEN]
      ) {
        ...getPullRequest
      }
  }
  
}
fragment getPullRequest on PullRequestConnection {
  edges {
    node {
      id
      title
      url
      baseRefName
      headRefName 
      reviewRequests {
        totalCount
      }
      reviewDecision
      createdAt
      permalink
      mergeable
      state
      ...getReviewer
    }
  }
}
fragment getReviewer on PullRequest {
  reviews(first: 10) {
    edges {
      node {
        state
        body
        comments(first: 10) {
          edges {
            node {
              body
            }
          }
        }
        author {
          login
        }
      }
    }
  }
}

