{{ if .Trackers }}
query PRs {
{{ range .Trackers }}
  {{ .Id }}: repository(name: "{{ .Repo }}", owner: "{{ .Owner }}") {
      pullRequests(
        orderBy: { field: CREATED_AT, direction: ASC }
        first: {{$.PrAmount}}
        states: [OPEN]
      ) {
        ...getPullRequest
      }
  }
  {{end}}
}
fragment getPullRequest on PullRequestConnection {
  edges {
    node {
      id
      title
      url
      baseRefName
      headRefName 
      reviewRequests {
        totalCount
      }
      reviewDecision
      createdAt
      permalink
      mergeable
      state
      ...getReviewer
    }
  }
}
fragment getReviewer on PullRequest {
  reviews(first: {{ .ReviewAmount }}) {
    edges {
      node {
        state
        body
        comments(first: {{ .CommentsAmount }}) {
          edges {
            node {
              body
            }
          }
        }
        author {
          login
        }
      }
    }
  }
}
{{ end }}
