# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: multi build

on:
  push:
    branches:
      - DarVoid-patch-1
    tags:
      - 'v*'
     

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64, 386]
        exclude: 
          - os: linux
            arch: arm64
          - os: windows
            arch: arm64
          - os: darwin
            arch: 386
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
     
    - name: Deps
      run: |
        go mod tidy

    - name: Build
      run: CGO_ENABLED=1 GOOS=${{matrix.os}} GOARCH=${{matrix.arch}} go build -o main-${{matrix.os}}-${{matrix.arch}}  *.go

    #- name: Test
    #  run: go test -v ./...
